In [1]:
import sys
def process_bar(num, total):
    """
    绘制CLI进度条

    Args:
        num (int): 当前完成的任务数量
        total (int): 任务的总数量
    """
    # 计算任务完成的比率
    rate = float(num) / total
    # 根据比率计算需要显示的进度条长度(最长50个字符)
    ratenum = int(50 * rate)
    # 构造进度条字符串
    # Progress: [+++++++          ]50%
    r = '\rProgress: [{}{}]{}%'.format('+' * ratenum, ' ' * (50 - ratenum), ratenum*2)
    # 在命令行中写入进度条，\r用于回到行首，不换行
    sys.stdout.write(r)
    # 刷新标准输出，确保进度条及时更新
    sys.stdout.flush()

In [2]:
process_bar(100,100)

Progress: [++++++++++++++++++++++++++++++++++++++++++++++++++]100%

In [4]:
for i in range(10000):
    process_bar(i, 10000)
process_bar(10000, 10000)

Progress: [++++++++++++++++++++++++++++++++++++++++++++++++++]100%

In [2]:
res = {}
res['u1'] = {}
res['u2'] = {}
res['u1']['i1'] = 1
res['u1']['i2'] = 2
res['u2']['i1'] = 3
res['u2']['i2'] = 4

In [8]:
print('u1' in res, 'a' in res)
print('u1' in res.keys())

True False
True


In [1]:
l1 = ['head1']
items = ['i1', 'i2']
print(l1 + items)

['head1', 'i1', 'i2']


xavier

In [1]:
import torch
import torch.nn as nn

# 假设我们有 4 个输入节点，3 个输出节点
n_in, n_out = 4, 3

# 创建一个权重张量，大小为 (n_out, n_in)
weight = torch.empty(n_out, n_in)

# 使用 Xavier 均匀分布初始化
nn.init.xavier_uniform_(weight)
print("Xavier Uniform Initialized Weights:")
print(weight)

# 再次创建一个权重张量
weight = torch.empty(n_out, n_in)

# 使用 Xavier 正态分布初始化
nn.init.xavier_normal_(weight)
print("\nXavier Normal Initialized Weights:")
print(weight)

Xavier Uniform Initialized Weights:
tensor([[-0.5021, -0.5029, -0.2428, -0.0213],
        [ 0.1326,  0.8364,  0.6794, -0.4628],
        [-0.7714,  0.1131, -0.6915, -0.2788]])

Xavier Normal Initialized Weights:
tensor([[ 0.7360,  0.1673, -0.1899,  0.2551],
        [ 0.0159, -0.4252, -0.0738, -0.3779],
        [ 1.3428,  0.0142,  0.0664, -0.6059]])


In [5]:
import torch
t1 = torch.rand((2,3))
print(t1)
t2 = torch.rand((2,3))
print(t2)
t3 = torch.cat([t1, t2], dim=0)
print(t3)

tensor([[0.3903, 0.7587, 0.7791],
        [0.7873, 0.4488, 0.4789]])
tensor([[0.8189, 0.5877, 0.4617],
        [0.2679, 0.7100, 0.6516]])
tensor([[0.3903, 0.7587, 0.7791],
        [0.7873, 0.4488, 0.4789],
        [0.8189, 0.5877, 0.4617],
        [0.2679, 0.7100, 0.6516]])


In [6]:
import torch

# 创建普通矩阵
dense_matrix = torch.tensor([[1, 0, 0], [0, 0, 3], [4, 0, 0]])

# 创建稀疏矩阵
indices = torch.tensor([[0, 1, 2], [0, 2, 0]])  # 非零元素的行和列索引
values = torch.tensor([1, 3, 4])  # 非零元素的值
sparse_matrix = torch.sparse_coo_tensor(indices, values, (3, 3))

print("Dense Matrix:\n", dense_matrix)
print("Sparse Matrix:\n", sparse_matrix)


Dense Matrix:
 tensor([[1, 0, 0],
        [0, 0, 3],
        [4, 0, 0]])
Sparse Matrix:
 tensor(indices=tensor([[0, 1, 2],
                       [0, 2, 0]]),
       values=tensor([1, 3, 4]),
       size=(3, 3), nnz=3, layout=torch.sparse_coo)


In [19]:
import numpy as np
import scipy.sparse as sp
import torch

def convert_sparse_mat_to_tensor(X):
    coo = X.tocoo()  # 转换为 COO 格式
    indices = torch.LongTensor([coo.row, coo.col])
    values = torch.from_numpy(coo.data).float()
    return torch.sparse_coo_tensor(indices, values, coo.shape)


def above(X):
    coo = X.tocoo()  # 转换为 COO 格式
    indices = torch.LongTensor(np.vstack([coo.row, coo.col]))
    print(type(indices))
    values = torch.from_numpy(coo.data).float()
    return torch.sparse_coo_tensor(indices, values, coo.shape)

# 创建一个 SciPy COO 稀疏矩阵
data = np.array([1, 3, 4])
row_indices = np.array([0, 1, 2])
col_indices = np.array([0, 2, 0])
sparse_matrix = sp.coo_matrix((data, (row_indices, col_indices)), shape=(3, 3))
print(f'sparse matrix:\n{sparse_matrix}')

# 转换为 PyTorch 稀疏张量
torch_sparse_tensor = convert_sparse_mat_to_tensor(sparse_matrix)
result = above(sparse_matrix)

print(torch_sparse_tensor)
print(result)


sparse matrix:
  (0, 0)	1
  (1, 2)	3
  (2, 0)	4
<class 'torch.Tensor'>
tensor(indices=tensor([[0, 1, 2],
                       [0, 2, 0]]),
       values=tensor([1., 3., 4.]),
       size=(3, 3), nnz=3, layout=torch.sparse_coo)
tensor(indices=tensor([[0, 1, 2],
                       [0, 2, 0]]),
       values=tensor([1., 3., 4.]),
       size=(3, 3), nnz=3, layout=torch.sparse_coo)


In [21]:
import torch
import torch.nn.functional as F

# 创建一个示例三维张量
x = torch.tensor([[[3.0, 4.0], 
                    [1.0, 2.0]],

                   [[2.0, 1.0], 
                    [4.0, 3.0]]])
print(x.shape)
# 沿着最后一个维度归一化
normalized_dim_neg1 = F.normalize(x, p=2, dim=-1)

print("原始张量:\n", x)
print("沿着最后一个维度归一化后的张量:\n", normalized_dim_neg1)


torch.Size([2, 2, 2])
原始张量:
 tensor([[[3., 4.],
         [1., 2.]],

        [[2., 1.],
         [4., 3.]]])
沿着最后一个维度归一化后的张量:
 tensor([[[0.6000, 0.8000],
         [0.4472, 0.8944]],

        [[0.8944, 0.4472],
         [0.8000, 0.6000]]])


In [27]:
x = torch.randn(2, 3)
x

tensor([[ 0.9729,  1.5272,  0.4359],
        [-0.1330, -0.5348,  0.4167]])

In [34]:
y = torch.stack((x, x), dim=0)
print(y.shape)
print(y)

torch.Size([2, 2, 3])
tensor([[[ 0.9729,  1.5272,  0.4359],
         [-0.1330, -0.5348,  0.4167]],

        [[ 0.9729,  1.5272,  0.4359],
         [-0.1330, -0.5348,  0.4167]]])


In [32]:
y1 = torch.stack((x, x), dim=1)
y1.shape
y1

tensor([[[ 0.9729,  1.5272,  0.4359],
         [ 0.9729,  1.5272,  0.4359]],

        [[-0.1330, -0.5348,  0.4167],
         [-0.1330, -0.5348,  0.4167]]])

In [33]:
y2 = torch.stack((x, x), dim=2)
y2.shape
y2

tensor([[[ 0.9729,  0.9729],
         [ 1.5272,  1.5272],
         [ 0.4359,  0.4359]],

        [[-0.1330, -0.1330],
         [-0.5348, -0.5348],
         [ 0.4167,  0.4167]]])

In [39]:
import torch
a = torch.randn(3,2)
b = torch.randn(3,2)
c = torch.mul(a,b)
print(c, c.shape)
d = torch.randn(2,3)
print(torch.mul(a,d))

tensor([[-0.0099,  2.3835],
        [-0.8588, -0.6546],
        [-1.1814, -0.4834]]) torch.Size([3, 2])


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1